source("R/functions.R")
if (!requireNamespace("data.table", quietly = TRUE)) stop("Install data.table")
library(data.table)
x <- fread("data/example/synthetic_mortality.csv")
text_cols <- grep("^DEBIDO", names(x), value = TRUE)
cie_cols <- grep("CIE", names(x), value = TRUE)
y <- classify_lightning_cases(x, text_cols, cie_cols)
stopifnot(sum(y$candidate_before_adjudication) == 5L)
stopifnot(sum(y$final_case) == 4L)
stopifnot(sum(y$excluded_cardiac_storm) == 1L)
stopifnot(all(y$final_case[c(1, 2, 3, 6)]))
stopifnot(!y$final_case[4], !y$final_case[5])
cat("Synthetic case-definition tests passed.\n")
