options(stringsAsFactors = FALSE, warn = 1)
source("R/functions.R")
ROOT <- repo_root(); setwd(ROOT)
source("scripts/01_build_validated_cohort.R")
source("scripts/02_run_analysis.R")
tryCatch(source("scripts/03_make_district_map.R"), error = function(e) message("Map warning: ", conditionMessage(e)))
source("scripts/04_quality_control.R")
source("scripts/05_export_public_release.R")
cat("\nCOMPLETE: numerical QC passed and the public aggregate release was created.\n")
